### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by johannesschobel** [Izhaki/mono.ts#1]
Dear @Izhaki ,

thanks for this wonderful starter project - really nice setup!
I was playing around, and i quite like it..

However, i stumbled upon the following issue:
I added a new `shape` package, where i tried to implement some demo shapes (e.g., `Rectangle`, `Circle` and so on). The base layout of this package is as follows:
```bash
packages
   ...
   shapes
      src
         models
            circle.ts
            rectangle.ts
            whatever.ts
```

I then added this `@geo/shapes` package to another package and tried importing the `Circle` class. While this works, the import statement is as follows:
```
import { Circle } from "@geo/shapes/src/models/circle";
```
which is - technically - ok, but the `src` within the path is kind of weird..

Is there a way to get around this?
In your example this does not happen, because you have everything in your `index.ts` defined. However, if you add a new file, you can easily reproduce this issue..

Maybe you can give me a hint and point me to the right direction?
All the best

**Comment by unzico** [comment]
> ```
> import { Circle } from "@geo/shapes/src/models/circle";
> ```

You should be able to import it using `dist` instead of `src`.
```
import { Circle } from "@geo/shapes/dist/models/circle";
```

Importing it from `"@geo/shapes"` would require you to export everything it in the dist's index file.
This may become annoying depending on the number of files you need to export.

Alternatively, you could create an index file on the `models` folder and export any subfiles from there, which shortens the import path to `"@geo/shapes/dist/models`.

**Comment by Izhaki** [comment]
Neither `dist` nor `src` should be part of your imports.

You could define your aliases like so in `tsconfig.json`:

```json
        "paths": {
            "@sample/*": ["node_modules/@sample/*/src"]
        }
```

You can see this at work in [this example](https://github.com/wixplosives/sample-monorepo/blob/master/packages/server/tsconfig.build.json)

Does this help?

**Comment by Izhaki** [comment]
Closing. Happy to reopen if the problem persist.
